//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.OrdersItems = new HashSet<OrdersItems>();
        }
    
        public int ID { get; set; }
        public string Article { get; set; }
        public int TypeID { get; set; }
        public int UnitID { get; set; }
        public decimal Price { get; set; }
        public int SupplierID { get; set; }
        public int ManufacturerID { get; set; }
        public int CategoryID { get; set; }
        public decimal Discount { get; set; }
        public int Stock { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Types Types { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersItems> OrdersItems { get; set; }
    }
}
